/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

import downloadItemsModel from "./DownloadItems.glb"

type GLTFResult = GLTF & {
  nodes: {
    Box_3: THREE.Mesh
    Mesh_1: THREE.Mesh
    Mesh: THREE.Mesh
    Cylinder_2: THREE.Mesh
    Cylinder_3: THREE.Mesh
    Cylinder_4: THREE.Mesh
    Cylinder_1_1: THREE.Mesh
    Cylinder_1_2: THREE.Mesh
    Cylinder_1_3: THREE.Mesh
    Quad_Sphere: THREE.Mesh
    Box_1: THREE.Mesh
    Box_2: THREE.Mesh
    Cylinder_5: THREE.Mesh
    Cylinder_6: THREE.Mesh
    Cylinder_7: THREE.Mesh
    Cylinder_8: THREE.Mesh
    Box_2_1: THREE.Mesh
    Box_2_2: THREE.Mesh
    Box_2_3: THREE.Mesh
    Box_2_4: THREE.Mesh
    Box_2_5: THREE.Mesh
    Box_2_6: THREE.Mesh
    Box_2_7: THREE.Mesh
  }
  materials: {
    Box_material: THREE.MeshPhysicalMaterial
  }
}

type DownloadItemsModelProps = {
  model: "Arcade" | "Chip" | "Disk"
}

export const DownloadItemsModel = ({
  model = "Chip",
}: DownloadItemsModelProps) => {
  const { nodes, materials } = useGLTF(downloadItemsModel) as GLTFResult
  return (
    <group dispose={null}>
      <group>
        {model === "Arcade" && (
          <group name="Arcade">
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box_3.geometry}
              material={materials.Box_material}
              position={[0, -0.5228, 0]}
              scale={7.8229}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_1.geometry}
                material={materials.Box_material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh.geometry}
                material={materials.Box_material}
              />
            </mesh>
            <group position={[0, -0.028, 0.4153]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_2.geometry}
                material={nodes.Cylinder_2.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_3.geometry}
                material={nodes.Cylinder_3.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_4.geometry}
                material={nodes.Cylinder_4.material}
              />
            </group>
            <group position={[0, -0.068, 0.4153]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_1_1.geometry}
                material={nodes.Cylinder_1_1.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_1_2.geometry}
                material={nodes.Cylinder_1_2.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_1_3.geometry}
                material={nodes.Cylinder_1_3.material}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Quad_Sphere.geometry}
              material={nodes.Quad_Sphere.material}
              position={[0, 0.0708, 0.4152]}
              scale={0.1544}
            />
          </group>
        )}
        {model === "Chip" && (
          <group name="Chip">
            <group rotation={[Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box_1.geometry}
                material={materials.Box_material}
                scale={146.7428}
              />
            </group>
            <group>
              <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Box_2.geometry}
                  material={materials.Box_material}
                  position={[-0.4982, -0.1247, 0.4793]}
                  scale={146.7428}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box_2_1.geometry}
                material={materials.Box_material}
                position={[-0.1693, 0.4793, -0.1247]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-146.7428, 146.7428, 146.7428]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box_2_2.geometry}
                material={materials.Box_material}
                position={[0.1595, 0.4793, -0.1247]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-146.7428, 146.7428, 146.7428]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box_2_3.geometry}
                material={materials.Box_material}
                position={[0.4884, 0.4793, -0.1247]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-146.7428, 146.7428, 146.7428]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box_2_4.geometry}
                material={materials.Box_material}
                position={[-0.4982, 0.4793, -0.1247]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[-146.7428, 146.7428, 146.7428]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box_2_5.geometry}
                material={materials.Box_material}
                position={[-0.1693, -0.4793, -0.1247]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={146.7428}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box_2_6.geometry}
                material={materials.Box_material}
                position={[0.1595, -0.4793, -0.1247]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={146.7428}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box_2_7.geometry}
                material={materials.Box_material}
                position={[0.4884, -0.4793, -0.1247]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={146.7428}
              />
            </group>
          </group>
        )}
        {model === "Disk" && (
          <group name="Disk" rotation={[-(Math.PI / 16), 0, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.9999, 0.9999]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_5.geometry}
                material={nodes.Cylinder_5.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_6.geometry}
                material={nodes.Cylinder_6.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_7.geometry}
                material={nodes.Cylinder_7.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_8.geometry}
                material={nodes.Cylinder_8.material}
              />
            </group>
          </group>
        )}
      </group>
    </group>
  )
}

useGLTF.preload("/DownloadItems.glb")
