name: Add Release to Changelog
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          header: "# Changelog"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_summary_template: "update changelog for %s changes"
